export {default as Home} from './Home.js'
export {default as Rooms} from './Rooms.js'
export {default as SingleRoom} from './SingleRoom.js'
export {default as Navbar} from './Navbar'
export {default as Error} from './Error.js'
